#!/usr/bin/env python

# Register the Debian error analyser
from dbtexmf.core import error
from dbtexmf.contrib.debian.errorhandler import DebianHandler
error.set_errhandler(DebianHandler())

from dbtexmf.dblatex import dblatex
dblatex.main('/usr/share/dblatex')
